"""InpWriter — 导出 EPANET INP 文件"""

import math
from typing import Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from wdrip.network import DripNetwork, EmitterNode


class InpWriter:
    """EPANET INP 文件导出器
    
    将 DripNetwork 导出为标准的 EPANET INP 格式，
    兼容 EPANET 2.2。
    """
    
    def __init__(self, network: 'DripNetwork'):
        self.network = network
        self.lines: List[str] = []
    
    def write(self, path: str):
        """写入 INP 文件"""
        self.lines = []
        
        self._write_title()
        self._write_junctions()
        self._write_reservoirs()
        self._write_pipes()
        self._write_pumps()
        self._write_valves()
        self._write_emitters()
        self._write_coordinates()
        self._write_options()
        self._write_end()
        
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(self.lines))
    
    def to_string(self) -> str:
        """返回 INP 字符串"""
        self.lines = []
        self._write_title()
        self._write_junctions()
        self._write_reservoirs()
        self._write_pipes()
        self._write_pumps()
        self._write_valves()
        self._write_emitters()
        self._write_coordinates()
        self._write_options()
        self._write_end()
        return "\n".join(self.lines)
    
    def _add(self, line: str = ""):
        self.lines.append(line)
    
    # ---- 各节 ----
    
    def _write_title(self):
        self._add("[TITLE]")
        self._add(f"; Generated by aQuaDrip v0.1")
        self._add(f"; Network: {self.network.name}")
        self._add("")
    
    def _write_junctions(self):
        self._add("[JUNCTIONS]")
        self._add(";ID               Elevation      Demand         Pattern")
        for nid, node in self.network.nodes.items():
            # 所有非 SourceNode 的节点，包括 EmitterNode
            if not hasattr(node, "source_type"):
                elev = getattr(node, "elevation", 0)
                demand = getattr(node, "demand", 0)
                # 转换 m³/s → LPS (EPANET 常用 LPS)
                demand_lps = demand * 1000 if hasattr(node, "emitter_k") else 0
                self._add(f"  {nid:<16} {elev:<15.3f} {demand_lps:<15.6f}  ")
        self._add("")
    
    def _write_reservoirs(self):
        self._add("[RESERVOIRS]")
        self._add(";ID               Head           Pattern")
        for nid, node in self.network.nodes.items():
            if hasattr(node, "source_type") and hasattr(node, "head"):
                head = getattr(node, "head", 0)
                self._add(f"  {nid:<16} {head:<15.3f}")
        self._add("")
    
    def _write_pipes(self):
        self._add("[PIPES]")
        self._add(";ID               Node1           Node2           Length     Diameter    Roughness   MinorLoss   Status")
        for lid, link in self.network.links.items():
            if hasattr(link, "pipe_type"):
                d_mm = link.diameter * 1000 if link.diameter < 1 else link.diameter
                self._add(
                    f"  {lid:<16} {link.from_node:<15} {link.to_node:<15} "
                    f"{link.length:<10.3f} {d_mm:<10.2f} {link.roughness:<10.1f} "
                    f"{link.minor_loss:<10.2f} {link.status}"
                )
        self._add("")
    
    def _write_pumps(self):
        self._add("[PUMPS]")
        self._add(";ID               Node1           Node2           Parameters")
        has_pump = False
        for lid, link in self.network.links.items():
            if hasattr(link, "pump_type"):
                has_pump = True
                # 简单泵: HEAD 模式
                q = getattr(link, "rated_flow", 0)
                h = getattr(link, "rated_head", 0)
                self._add(
                    f"  {lid:<16} {link.from_node:<15} {link.to_node:<15} "
                    f"HEAD {h:.2f}"
                )
        if not has_pump:
            self._add("; (无水泵)")
        self._add("")
    
    def _write_valves(self):
        self._add("[VALVES]")
        self._add(";ID               Node1           Node2           Diameter    Type    Setting      MinorLoss")
        has_valve = False
        for lid, link in self.network.links.items():
            if hasattr(link, "valve_type"):
                has_valve = True
                vtype = str(link.valve_type.name).upper()
                d_mm = link.diameter * 1000 if link.diameter < 1 else link.diameter
                self._add(
                    f"  {lid:<16} {link.from_node:<15} {link.to_node:<15} "
                    f"{d_mm:<10.2f} {vtype:<8} {link.setting:<12.2f} {link.minor_loss:<.2f}"
                )
        if not has_valve:
            self._add("; (无阀门)")
        self._add("")
    
    def _write_emitters(self):
        self._add("[EMITTERS]")
        self._add(";Junction         Coefficient     Exponent")
        has_emitter = False
        for nid, node in self.network.nodes.items():
            if hasattr(node, "emitter_k") and node.emitter_k > 0:
                has_emitter = True
                # EPANET 用 LPS 单位: 1 L/h = 0.0002778 LPS
                coeff_lps = node.emitter_k / 3600
                self._add(f"  {nid:<16} {coeff_lps:.8f}     {node.emitter_x}")
        if not has_emitter:
            self._add("; (无滴头)")
        self._add("")
    
    def _write_coordinates(self):
        self._add("[COORDINATES]")
        self._add(";Node             X-Coord         Y-Coord")
        for nid, node in self.network.nodes.items():
            if hasattr(node, "x") and hasattr(node, "y"):
                self._add(f"  {nid:<16} {node.x:<15.3f} {node.y:<15.3f}")
        self._add("")
    
    def _write_options(self):
        self._add("[OPTIONS]")
        units = "LPS" if self.network.units == "SI" else "GPM"
        headloss = "H-W"
        self._add(f"  Units       {units}")
        self._add(f"  Headloss    {headloss}")
        self._add(f"  Pattern     1")
        self._add("")
    
    def _write_end(self):
        self._add("[END]")
